
const questionsAboutMen = [
    // {
    //     question : ,
    //     clue : ,
    //     choiceA : , 
    //     choiceB: ,
    //     choiceC: , 
    //     choiceD: ,
    //     correctAnswer :
    // },
    {
        question : 'Who asked the Israelites to separate from their foreign wives?',
        clue : 'Ezra 10:10, 11: Then Ezra the priest rose and said to them: "You have acted unfaithfully by marrying foreign women, and so you have added to the guilt of Israel."',
        choiceA : 'Asa', 
        choiceB : 'Moses',
        choiceC : 'Nehemiah', 
        choiceD : 'Ezra',
        correctAnswer : 'D',
    },
    // questionsAboutMen0.choiceD -> Ezra
    {
        question : 'He was Eunice’s son and Lois’s grandson.',
        clue : '2 Timothy 1:5: For I recall your unhypocritical faith, which dwelled first in your grandmother Loʹis and your mother Euʹnice, but which I am confident is also in you.',
        choiceA : 'Philip',
        choiceB : 'Silas',
        choiceC : 'Paul',
        choiceD : 'Timothy',
        correctAnswer : 'Timothy',
    },
    {
        question : 'The judge that Jehovah used to defeat a Midian army with only 300 men.',
        clue : 'Judges 7:7: Jehovah now said to Gidʹe·on: “I will save you with the 300 men who lapped the water, and I will give Midian into your hand. But let all the other people go back home.”', 
        choiceA : 'Joshua', 
        choiceB : 'Gideon', 
        choiceC : 'Samuel', 
        choiceD : 'Jephthah',
        correctAnswer : 'Gideon',
    },
    {
        question : 'Jehovah set up a sign for him “in order that no one finding him would strike him.”',
        clue : 'Genesis 4:15: So Jehovah said to him: “For that reason, anyone who kills Cain will suffer vengeance seven times.” So Jehovah set up a sign for Cain in order that no one finding him would strike him.',
        choiceA : 'Abel', 
        choiceB : 'Cain', 
        choiceC : 'Enoch', 
        choiceD : 'Noah',
        correctAnswer : 'Cain',
    },
    {
        question : 'He asked Jesus: “Are you the King of the Jews?”',
        clue : 'Matthew 27:2: After binding him, they led him off and handed him over to Pilate, the governor.', 
        choiceA : 'Herod', 
        choiceB : 'Nicodemus', 
        choiceC : 'Pilate', 
        choiceD : 'Philip',
        correctAnswer : 'Pilate',
    },
    {
        question : 'Jehovah, for the first time, allowed this man to have meat as food.',
        clue : 'He and his family survived the Flood.', 
        choiceA : 'Moses', 
        choiceB : 'Noah', 
        choiceC : 'Aaron', 
        choiceD : 'Eleazer',
        correctAnswer : 'Noah',
    },
    {
        question : 'Who, other than Moses, appeared at the transfiguration of Jesus?',
        clue : 'Mark 9:4: Also, Elijah with Moses appeared to them, and they were conversing with Jesus.', 
        choiceA : 'Eli', 
        choiceB : 'Enoch', 
        choiceC : 'John', 
        choiceD : 'Elijah',
        correctAnswer : 'Elijah',
    },
    {
        question : 'He is a friend of Jesus who was raised from the dead.',
        clue : 'John 11:43: When he had said these things, he cried out with a loud voice: “Lazarus, come out!”', 
        choiceA : 'Matthew', 
        choiceB : 'Judah', 
        choiceC : 'Lazarus', 
        choiceD : 'John',
        correctAnswer : 'Lazarus',
    },
    {
        question : 'He became hot with anger with Jehovah for not destroying Nineveh.',
        clue : 'He was swallowed by a huge fish.—Jonah 1:17',
        choiceA : 'Jonah', 
        choiceB : 'Job',
        choiceC : 'Hezekiah', 
        choiceD : 'Hagai',
        correctAnswer : 'Jonah',
    },
    {
        question : 'Who formed a golden calf while Moses was on Mount Sinai?',
        clue : 'Exodus 32:3: So all the people began taking off the gold earrings that were in their ears and bringing them to Aaron.', 
        choiceA : 'Jeroboam', 
        choiceB : 'Aaron',
        choiceC : 'Korah',
        choiceD : 'Abiram',
        correctAnswer : 'Aaron',
    },
    {
        question : 'The father of John the Baptizer.',
        clue : 'Luke 1:13: However, the angel said to him: “Do not be afraid, Zechariah, because your supplication has been favorably heard, and your wife Elizabeth will bear you a son, and you are to name him John.', 
        choiceA : 'Zerubbabel', 
        choiceB : 'Zedekiah', 
        choiceC : 'Zechariah', 
        choiceD : 'Zadok',
        correctAnswer : 'Zechariah',
    },
    {
        question : 'His own female donkey spoke to him after beating it for three times.',
        clue : 'Numbers 22:28: Finally Jehovah caused the donkey to speak, and it said to Balaam: “What have I done to you to make you beat me these three times?”', 
        choiceA : 'Balaam', 
        choiceB : 'Balak', 
        choiceC : 'Hosea',
        choiceD : 'Barak',
        correctAnswer : 'Balaam',
    },
    {
        question : 'After Ananias talked to him about being anointed by holy spirit, “what looked like scales fell from his eyes, and he recovered his sight.”',
        clue : 'Acts 9:17: So Ananias went and entered the house, and he laid his hands on him and said: “Saul, brother, the Lord Jesus, who appeared to you on the road along which you were coming, has sent me so that you may recover sight and be filled with holy spirit.”', 
        choiceA : 'Peter', 
        choiceB : 'James', 
        choiceC : 'John', 
        choiceD : 'Paul',
        correctAnswer : 'Paul',
    },
    {
        question : 'Who, because of his poor eyesight, blessed Jacob instead of Esau?',
        clue : 'Genesis 27:27: Then Isaac his father said to him: “Come near, please, and kiss me, my son.” So he came near and kissed him, and he could smell the scent of his garments. Then he blessed him.', 
        choiceA : 'Abraham', 
        choiceB : 'Isaac', 
        choiceC : 'Joseph', 
        choiceD : 'Jacob',
        correctAnswer : 'Isaac',
    },
    {
        question : 'King Nebuchadnezzar gave this prophet of Jehovah the name ‘Belteshazzar’.',
        clue : 'Daniel 5:12: For Daniel, whom the king named Bel·te·shazʹzar, had an extraordinary spirit and knowledge and insight to interpret dreams, to explain riddles, and to solve knotty problems.', 
        choiceA : 'Daniel', 
        choiceB : 'Jonah', 
        choiceC : 'Shadrach', 
        choiceD : 'Meshach',
        correctAnswer : 'Daniel',
    },
    {
        question : 'After he lost everything he had, "Jehovah gave him double what he had before" for his faithfulness in the end.',
        clue : 'Job 42:10: "After Job had prayed for his companions, Jehovah removed Job’s tribulation and restored his prosperity. Jehovah gave him double what he had before."',
        choiceA : 'Job', 
        choiceB : 'Joseph', 
        choiceC : 'Moses', 
        choiceD : 'Aaron',
        correctAnswer : 'Job',
    },
    {
        question : 'A Jew who refused to prostrate himself before the Amalekite Haman.',
        clue : 'Esther 3:2: And all the king’s servants who were in the king’s gate would bow low and prostrate themselves to Haman, for this is what the king had commanded respecting him. But Mordecai refused to bow low or prostrate himself.', 
        choiceA : 'Meshach', 
        choiceB : 'Shadrach', 
        choiceC : 'Mordecai', 
        choiceD : 'Abednego',
        correctAnswer : 'Mordecai',
    },
    {
        question : 'One of David’s sons who was highly praised for his handsome appearance in all Israel.',
        clue : '2 Samuel 14:25: Now in all Israel, no man was as highly praised for his handsome appearance as Absalom. From the sole of his foot to the crown of his head, there was no flaw in him.', 
        choiceA : 'Solomon', 
        choiceB : 'Absalom', 
        choiceC : 'Adonijah', 
        choiceD : 'Amnon',
        correctAnswer : 'Absalom',
    },
    {
        question : 'An apostle who spread a big reception feast for Jesus in his house. He’s also called ‘Levi’.',
        clue : 'Luke 5:29: Then Levi spread a big reception feast for him in his house, and there was a large crowd of tax collectors and others who were dining with them.', 
        choiceA : 'Matthew', 
        choiceB : 'Mark', 
        choiceC : 'John', 
        choiceD : 'Luke',
        correctAnswer : 'Matthew',
    },
    {
        question : 'Delilah betrayed this Nazarite judge in exchange for 1,100 silver pieces.',
        clue : 'Judges 16:18: So he finally opened his heart to her, saying: “A razor has never touched my head, because I am a Nazirite of God from birth. If I am shaved, my power will leave me and I will grow weak and become like all other men.”', 
        choiceA : 'Gideon', 
        choiceB : 'Barak', 
        choiceC : 'Joshua', 
        choiceD : 'Samson',
        correctAnswer : 'Samson',
    },
];
